Replace 'past speakers' with 'current speakers' section
mainmatter/eurorust.eu pull request #308
Opened 2023-04-01 06:47 UTC by oscard0m

# Description
- Change title from **Past Speakers** to **Speakers**
- Remove old speakers
- Add speakers
   - Niko Matsakis
   - ~Ashley Williams~ TBA
   - ~Iryna Shestak~ TBA
   - ~Lisa Passing~ TBA
- Add 'Moderator' section
   - Sara Vieira  

## Out of scope
Changing how the title of the section looks like will be addressed in https://github.com/mainmatter/eurorust.eu/issues/330

# Context
Fixes #292
Fixes #326
Fixes #330

2023-05-24 12:55 UTC, oscard0m commented
Once re-approved, let me know if we can go live.

2023-05-24 13:14 UTC, oscard0m commented
> doesn't it look strange to have one person in the middle of a huge empty screen? I understand this seemed to be the easiest way to just duplicate the Speakers section, but I would never come up with a UI solution like this.
> 
> what do you think?
> 
> <img alt="Screenshot 2023-05-24 at 15 02 38" width="2000" src="https://user-images.githubusercontent.com/78347340/240612648-503edf8f-8d54-4acb-ab1f-4f207f350b82.png">

@davidhajba Do you mean the space between elements is too much or do you mean we should re-think the design for this in Sketch?

2023-05-24 13:35 UTC, davidhajba commented
things start to look very different than the [ORIGINAL UI](https://www.sketch.com/s/635e7434-03d6-46c0-8dad-fa9f7fce9021/a/VrZgkDr)

I think we have 3 options:
* Add everything quickly without any conscious UI planning 
* Collect all the new and possible future elements and rethink the UI - so I can be responsible for the overall look
* Add everything quickly now & meanwhile Collect all the new and possible future elements and rethink the UI

@marcoow please let me know how to proceed

2023-05-24 13:48 UTC, marcoow commented
We'll add this as it is for now. We can rethink things but can't redo the entire layout – we can't invest huge amounts of time in these conference websites

2023-05-24 14:09 UTC, davidhajba commented
`We can rethink things but can't redo the entire layout – we can't invest huge amounts of time in these conference websites`
thank you - I understand

2023-05-30 10:47 UTC, marcoow requested changes

2023-05-30 10:47 UTC, marcoow commented on content/_index.md
> +	web="https://lucumr.pocoo.org/"
```suggestion
	name="Iryna Shestak"
	company="Apollo GraphQL"
	job_title="Senior Staff Rust Engineer"
	image="armin-ronacher.webp"
	twitter="_lrlna"
	web="https://toot.cafe/@lrlna"
```

We're not announcing Armin (for now, maybe later). We forgot Iryna here anyway though 🤦

2023-05-30 11:44 UTC, marcoow approved these changes

2023-05-30 11:44 UTC, oscard0m commented
@marcoow Do I merge? 🚀

2023-05-30 11:53 UTC, marcoow commented
no, Sarah and Emma will let you know next week

2023-06-07 11:49 UTC, marcoow commented
Sara isn't yet announced as the moderator

2023-06-07 11:58 UTC, merged