Add workshops
mainmatter/eurorust.eu pull request #454
Opened 2024-04-25 13:14 UTC by yaigrie

2024-04-25 14:19 UTC, marcoow reviewed
I don't think this is quite there yet design-wise – should we first figure out a design in Sketch?

2024-04-25 14:23 UTC, yaigrie commented
@marcoow Sure thing! Do we only need the single workshop pages or anything else?

2024-04-26 13:03 UTC, marcoow requested changes
Should the mentor image be square like the speaker images on the main landing page? 
![Bildschirmfoto 2024-04-26 um 15 02 30](https://github.com/mainmatter/eurorust.eu/assets/1510/8a3b4441-7370-4bdc-949f-7a1023d2210c)

2024-04-26 13:03 UTC, marcoow commented on templates/sections/schedule-temp.html
> -    </div>
Let's keep this section and just remove the _"Details about the…"_

2024-04-26 13:03 UTC, marcoow commented on templates/sections/workshop-schedule.html
> +    <h2 class="mb-4">Experience Rust in action</h2>
```suggestion
    <h2 class="mb-4">Deepen your Rust skills hands-on!</h2>
```

2024-04-26 13:03 UTC, marcoow commented on templates/sections/workshop-venue.html
> +				target="_blank" rel="noopener noreferrer">Check on Map</a>
The workshops aren't in the conference venue but the workshop is tba. This needs to repeat the text from the main landing page: "The EuroRust workshops will take place in a separate venue…" with a placeholder image

2024-04-26 14:40 UTC, marcoow commented on templates/sections/workshop-schedule.html
> +    <h2 class="mb-4">Experience Rust in action</h2>
@yaigrie let's still do this as well please

2024-04-26 14:41 UTC, marcoow reviewed
Let's still make the mentor images square – I think `aspect-ratio: 1/1;` only works in a few browsers

2024-04-26 15:27 UTC, marcoow commented
@yaigrie https://github.com/mainmatter/eurorust.eu/pull/454#discussion_r1581134096 🙏

2024-04-26 15:38 UTC, LukeMathWalker commented on content/workshops/async-rust.md
> +title = "Rediscovering the Future: a deep dive into the development of async Rust"
```suggestion
title = "Rediscovering the Future: a deep dive into async Rust"
```

I think it works better if it's a bit shorter.

2024-04-28 13:40 UTC, marcoow approved these changes

2024-04-29 06:37 UTC, merged